### ISSUE TITLE
remove

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/rpmbuild-bot#4]
add a remove command to remove a package from the rpm repo. Sometimes you need to upload more than 1 incarnation of a package, eg xyz-1 and xyz-2, as xyz-1 contained errors. So after uploading xyz-2 we should remove xyz-1, as it will never be moved to another repo at all. Right now we do that by hand.

**Comment by dmik** [comment]
This is really needed as deleting them by hand is a pain.

**Comment by dmik** [comment]
After having implemented the remove command I just realized that it's not actually what we normally want. It may be a bad idea to completely remove RPMs even from the experimental repository (needless to say about the release one). Especially when some time passes and a general cleanup is performed so that the details of this or that version vanish from the maintainer's head. There may be a need to look up on some intermediate build and it won't be very good if it has gone forever.

There is a better idea: have a "trashcan" for unneeded packages. It's really simple to implement: just add another repository which is never officially published (it may be even processed with `createrepo` in which case it can be used as a real repo to install RPMs from if a need arises). I will do that for the BWW repository group.

The remove command will still be there for emergency cases where it's absolutely clear that a set of cooked RPMs can be safely sent to the eternity (or when a cleanup in the attic is needed because of low space condition or such).
