### ISSUE TITLE
Moving of logs

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/rpmbuild-bot#5]
When moving a package from one repo to the other, it also moves the logs. After moving the logs, it deletes all not moved logs of this specifiv rpm. As the bot does a os.rmdir(o.path.dirname(from_log)) around line 1657. And as this results in a DELETE command for the webdav server it deletes the complete logs. As webdav deletes recursive.

**Comment by dmik** [comment]
Just to clarify: It appears to be a bug of the WebDAV plugin in NDFS. NDFS is an IFS (an installable OS/2 file system) and must behave according to the IFS specs. According to them, deleting a non-empty directory must result into an error. When issuing the DELETE command, the WebDAV plugin relies on the server reply and the server is configured to be fine with that, apparently. So is the plugin. A proper solution here is to fix the WebDAV plugin (or may be even NDFS itself so that it would automatically protect from all other plugins with similar behavior) by making it check for the directory contents before deleting it. But we don't have NDFS sources (not sure about the WebDAV plugin) and generally have no time for that now so I will simply provide a workaround in the bot (by checking the dir contents).

Note that the NDFS problem is actually a MAJOR security FLAW which actually affects all OS/2 applications dealing with directory deletion and someone should address this issue sooner or later.
